### ISSUE TITLE
1.2.3 Calculate use case points for effort estimation

### ISSUE THREAD

**Issue by LilZBJ** [Mhidayah19/INF2001-P5_1#13]
1. Task title ID: 
#13

2. What is this task about? Describe in detail
This task will calculate the use case points based on the use case scenarios presented, and calculate the complexity of the project in terms of hours needed. The task will utilize use case points (UCP) to calculate the hours, and take into account the number of transactions between the system and user, then identifying the actors, before calculating the complexity factor, and lastly, accounting for environmental factors.

3. What are the goals of the task? Describe in detail
To come up with the use case points after all team members complete their respective use cases, to help to determine an accurate estimate of the man hours required based on the use case scenarios.
4. Success or completion criteria. Describe in detail
When the calculations are complete, and a viable range of possible man hours is calculated, the task is considered to have succeeded.
5. Allocated time
About 1 week, 3 days time (12 sep to 22 sep)

6. Start and end date for the issue/task
(12 sep to 22 sep)

7. Who is the owner? Owner is the person in charge of the task and should be created and maintained by the owner.
Alessandra 

8. Task Status. Usually under "To-Do".
To-do
9. What is the priority of this task?
High priority

**Comment by allyyyyyyyyyyy** [comment]
1.	Describe the work done in detail
(Calculation of use case points were calculated and was used to calculate complexity factor.)

2.	Has this work been committed to the repo?
(Work has been committed to the repository on github under INF-2001-P5_1 on 12th September 2023)

3.	How does the work affect success of completion criteria?
(Range of possible man hours is calculated.)

4.	Start and end date of the work done:
(Start date: 12th September 2023 to 22nd September, 2023)
