### ISSUE TITLE
1.1.6  Email client with follow-up questions (2nd email)

### ISSUE THREAD

**Issue by LilZBJ** [Mhidayah19/INF2001-P5_1#15]
Task title ID:
#15

What is this task about? Describe in detail
To email the client with follow-up questions that were unanswered from our client meeting and first email.

What are the goals of the task? Describe in detail
To ensure confirm on the non-functional requirements of the client's software.

Success or completion criteria. Describe in detail
It would mean all the questions are being answered without any more doubts regarding the software.

Allocated time
3 days

Start and end date for the issue/task
Start date: 17th September 2023 (Sunday)
End date: 20th September 2023 (Wednesday)

Who is the owner? Owner is the person in charge of the task and should be created and maintained by the owner.
Owner: 2201905, Awil Alessandra Antoinette Javier (allyyyyyyyyyyy)

Task Status. Usually under "To-Do".
To-Do

What is the priority of this task?
High

**Comment by allyyyyyyyyyyy** [comment]
1.	Describe the work done in detail
(The 2nd follow-up email was sent to the client on 18th September 2023, Monday. We received the client's response on the 20th September 2023, Wednesday. The team managed to ask these questions:

Q1: The system shall not experience downtime of more than 1 hour per week(168 hours) of operation.
A1: Yes
Q2: The system shall encrypt sensitive data such as passwords using Secure Hash Algorithm(SHA)-256.
A2: Please propose.
Q3: The system shall send and receive data using HyperText Transfer Protocol (Secure) (HTTPS) to prevent man-in-the-middle attacks.
A3: Please propose.
Q4: The website shall have a valid Secure socket layer (SSL) certificate.
A4: Please propose.
Q5: Staff, managers, and IT administrators shall be able to learn all the functions of the system in under 5 hours. After this training, errors made by experienced users shall not exceed 3 per hour of system use.
A5: Functionalities should be self-explanatory and perhaps we can try out the software.
Q6: The system shall respond to user clicks in under 0.5 seconds.
A6: Instantaneous.
Q7: The web-based application shall be able to support the five most used browsers: Google Chrome, Safari, Edge, Samsung Internet, and Mozilla Firefox.
A7: It should support these.)

2.	Has this work been committed to the repo?
(Work has been committed to the repository on github under INF-2001-P5_1 on 18th September 2023)

3.	How does the work affect success of completion criteria?
(We now do not have any doubts in regards to how our software would turn out.)

4.	Start and end date of the work done:
(Start date: 18th September 2023 to 20th September, 2023)
