### ISSUE TITLE
1.3.5 Activity diagram

### ISSUE THREAD

**Issue by LilZBJ** [Mhidayah19/INF2001-P5_1#18]
1. Task title ID
#18

3. What is this task about? Describe in detail
This task is about creating activity diagram that models the flow of the activities of the scheduling system. I've created 2 activity diagrams that describe the flow of airline manager allocate job to pilot and pilot adding availability

5. What are the goals of the task? Describe in detail
Goals of this task is to visualize the exact flow that each actor such as airline manager and pilot will be going through in order achieve the task of allocate job to pilot and adding availability as well.

6. Success or completion criteria. Describe in detail
Completing criteria means the user has no confusion on how the flow is going to look like or there is no gaps in between while trying to achieve the goal of the task. It also means covering all the possible flow of each task.

7. Allocated time
5 days

8. Start and end date for the issue/task
18/09/23 - 22/09/23

9. Who is the owner? 
Reness

11. Task Status. 
Completed

12. What is the priority of this task?
Low Priority

**Comment by Thrith10** [comment]
i. Describe the work done in detail
I've created the activity diagram for 2 of the tasks that can achieved using the scheduling system which airline manager allocate job to pilot and pilot add availability

ii. Has this work been committed to the repo?
Yes can refer to it below.

iii. How does the work affect success of completion criteria?
We can have clear view of the flow while using the scheduling system and also was able to understand the perspectives of the user while navigating through the system

iv. Start and end date of the work done
18/09/23 - 22/09/23

![Image](https://github.com/Mhidayah19/INF2001-P5_1/assets/116250188/2b7bee5d-fce9-4016-bc26-bdc82d43a73e)
![Image](https://github.com/Mhidayah19/INF2001-P5_1/assets/116250188/69495ce6-6b7f-41e0-9795-7191f3b4bb7e)
