### ISSUE TITLE
2.3.1 Class diagram

### ISSUE THREAD

**Issue by allyyyyyyyyyyy** [Mhidayah19/INF2001-P5_1#23]
1. Task title ID: #23

2. What is this task about? 
Create Object Oriented Class Diagram

3. What are the goals of the task?
The goal of the task is to visually depict the structure and relationships of classes in a software system, facilitating design, communication, and documentation throughout the software development process.

4. Success or completion criteria. 
The completion criteria is when we can accurately represent the classes, their attributes, methods, and relationships within the software system, ensuring that it aligns with the system's design goals and requirements.

5. Allocated time
25 days

6. Start and end date for the issue/task
Start date: 3 October 2023 
End date: 28 October 2023

7. Who is the owner? Owner is the person in charge of the task and should be created and maintained by the owner.
Owner: Awil Alessandra Antoinette Javier @allyyyyyyyyyyy 
Reness Ravichandran @Thrith10 

8. Task Status. Usually under "To-Do".
Status: To-Do

9. What is the priority of this task?
High priority

**Comment by Thrith10** [comment]
1. Describe the work done in detail 
Created the class diagram based on the use case diagram and functional and non-functional requirements. Created multiple entities which includes users, flight assignment, flight assignment availability, aircraft, pilot workload & preference. Accompanied with their controller class and respective UI inside the boundary classes.

2. Has this work been committed to the repo?
Yes

3. How does the work affect success of completion criteria?
Class diagram sets up the base for the upcoming diagrams such as component diagram & sequence diagrams.

4. Start and end date of the work done
03/10/23 - 28/10/23



![Image](https://github.com/Mhidayah19/INF2001-P5_1/assets/116250188/7bc20b6a-1a28-473d-af68-523fb1fc16a5)
