### ISSUE TITLE
2.1.1 Sequence diagram : Use case 2: View monthly flight assignments

### ISSUE THREAD

**Issue by allyyyyyyyyyyy** [Mhidayah19/INF2001-P5_1#26]
1. Task title ID:  #26

2. What is this task about? Describe in detail
The creation of a sequence diagram for use case 2, View monthly flight assignment. The sequence diagram will specify the main flow and alternate scenarios as detailed in the report.

3. What are the goals of the task? Describe in detail
To create a complete and accurate sequence diagram that represents and reflects scenarios that are stated in the use case.

4. Success or completion criteria. Describe in detail
Completion of the sequence diagram with relevant scenarios inside.

5. Allocated time
9 October 2023 (Mon) to 17 Oct 2023 (Tue)

6. Start and end date for the issue/task
9 October 2023 (Mon) to 17 Oct 2023 (Tue)

7. Who is the owner? Owner is the person in charge of the task and should be created and maintained by the owner.
Awil Alessandra Antoinette Javier (allyyyyyyyyyyy), Lim Jun Hui (jhlim0079)

8. Task Status. Usually under "To-Do".
High-priority

9. What is the priority of this task?
High.

**Comment by Thrith10** [comment]
Describe the work done in detail
sequence diagram for uc2 is about getting the monthly flight assignments of the pilots that are assigned by the airline managers. 

Has this work been committed to the repo?
yes

How does the work affect success of completion criteria?
can move forward with the understanding of the sequence diagram flow 

Start and end date of the work done
3 oct to 28 oct
