### ISSUE TITLE
2.3.2 Work breakdown structure

### ISSUE THREAD

**Issue by LilZBJ** [Mhidayah19/INF2001-P5_1#29]
Task title ID:
2.3.2 Work breakdown structure#29

What is this task about? Describe in detail
Update work breakdown structure (WBS) in order to break down larger, more complex tasks into smaller, individually managed tasks. A task will not have more than 6 sub-components to it. It will serve as a complement to the Gantt chart 

What are the goals of the task? Describe in detail
The WBS will serve as a tasking board to allocate individual components of a complex task to different team members. With the WBS in place, team members will have a better idea of what tasks to do for which component, and have a better understanding of how the component complements the completion of the main task.

Success or completion criteria. Describe in detail
The creation of the WBS can be considered complete when all essential activities, including the Administrative, requirement gathering, Use cases, and workflow related portions for part Milestone 1(M1) have been implemented. In addition, the WBS must implement major sections of part M2 and M3, though dividing them into subtasks at this stage is still unnecessary.

Allocated time
3 oct to 28 oct

Start and end date for the issue/task
3 oct to 28 oct

Who is the owner? Owner is the person in charge of the task and should be created and maintained by the owner.
(Owner: 2201660, Sim Xin Rong (Github: LilZBJ))

Task Status. Usually under "To-Do".
Completed.

What is the priority of this task?
High

**Comment by LilZBJ** [comment]
1. Describe the work done in detail 
WBS updated and put into report

2. Has this work been committed to the repo?
Included the updated WBS below 

3. How does the work affect success of completion criteria?
Breaks down tasks for team members

4. Start and end date of the work done
3 oct to 28 oct

**Comment by Thrith10** [comment]
![Image](https://github.com/Mhidayah19/INF2001-P5_1/assets/116250188/5b7304a8-6e6a-4990-ad7d-a0eb12583f37)
