### ISSUE TITLE
3.0 M3 Report

### ISSUE THREAD

**Issue by Mhidayah19** [Mhidayah19/INF2001-P5_1#42]
Task title ID: #42

What is this task about?
Write all our project content into M3 report

What are the goals of the task?
The goal of this is to ensure all the M3 requirements gathering and workflow are in the report

Success or completion criteria.
The report has to be in the correct format and non section is missing or incorrect

Allocated time
19 days.

Start and end date for the issue/task
Start date: 06 November 2023 End date: 25 November 2023

Who is the owner? Owner is the person in charge of the task and should be created and maintained by the owner.
Owner: Hid @Mhidayah19, Reness @Thrith10, Ally @allyyyyyyyyyyy, Jun Hui @ztawei, Sim Xin Rong @LilZBJ 

Task Status. Usually under "To-Do".
Status: To-Do

What is the priority of this task?
Medium priority

**Comment by Thrith10** [comment]
[M3 Report.pdf](https://github.com/Mhidayah19/INF2001-P5_1/files/13464488/M3.Report.pdf)

i. Describe the work done in detail
Team report for part Milestone 3 (M3) updated and completed. Relevant sections have been filled with information and images, along with necessary explanations.

ii. Has this work been committed to the repo?
Yes, included below

iii. How does the work affect success of completion criteria?
The work done finishes the report, which will be submitted in PDF format, and is a critical component of part M3.

iv. Start and end date of the work done
6 Nov 2023 to 25 Nov 2023

**Comment by Thrith10** [comment]
.
