### ISSUE TITLE
3.7 Video Presentation Prep

### ISSUE THREAD

**Issue by Mhidayah19** [Mhidayah19/INF2001-P5_1#44]
Task title ID: #44

What is this task about?
A Recording of a Demo of the project prototype 

What are the goals of the task?
To present and demo of the prototype, showcasing the project product

Success or completion criteria.
A video 

Allocated time
6 days

Start and end date for the issue/task
Start date: 19 November 2023 End date: 25 November 2023

Who is the owner? Owner is the person in charge of the task and should be created and maintained by the owner.
Owner: Sim Xin Rong

Task Status. Usually under "To-Do".
Status: To-Do

What is the priority of this task?
Medium priority

**Comment by LilZBJ** [comment]
Describe the work done in detail
Video filmed in MP4 format addressing as many issues solved by our prototype wireframe as possible within the time limit.
Video link: [(https://www.youtube.com/watch?v=ECAvcHeNlKs)]

Has this work been committed to the repo?
Link to youtube has been added to the repo

How does the work affect success of completion criteria?
One component of submission M3 is the video report, so the completion of the video completes the task. 

Start and end date of the work done:
Start date: 19 November 2023 End date: 25 November 2023
