### ISSUE TITLE
1.2.2 Use case descriptions

### ISSUE THREAD

**Issue by LilZBJ** [Mhidayah19/INF2001-P5_1#7]
1. Task title ID: 
(Task ID #7)

2. What is this task about? Describe in detail
Write a use case description for every use cases we have.

3. What are the goals of the task? Describe in detail
To ensure all the use cases has been describe thoroughly.

4. Success or completion criteria. Describe in detail
All the use cases description table has been filled up and placed in the appendix section of the report

5. Allocated time
1 week

6. Start and end date for the issue/task
Start date: 12th September 2023 (Tuesday)
End date: 19th September 2023 (Tuesday) 

7. Who is the owner? Owner is the person in charge of the task and should be created and maintained by the owner.
Owner: 2202150, Muhammad Hidayah (Mhidayah19)

8. Task Status. Usually under "To-Do".
To-Do

9. What is the priority of this task?
Medium

**Comment by Mhidayah19** [comment]
i. Describe the work done in detail
After the use case diagram has been produced, each use cases will have a table with specific descriptions which include primary actor, pre-conditions, post-conditions , main scenarios and alternate scenarios.

ii. Has this work been committed to the repo?
It is updated in our report and google docs but couldn't update in the repo

iii. How does the work affect success of completion criteria?
We will have a clearer understanding on each use case and its purpose. So we can move forward in developing the functions 

iv. Start and end date of the work done
12/09/23 - 19/09/23
