### ISSUE TITLE
1.0.2 Group project introduction and how to address issues

### ISSUE THREAD

**Issue by LilZBJ** [Mhidayah19/INF2001-P5_1#9]
Task title ID:
Group project introduction(Task ID #9)

What is this task about?
Writing the introduction for the project, into the report.

What are the goals of the task?
The task involves creating the introduction for our project report.

Success or completion criteria. Describe in detail
The task will be considered successfully completed when the project's introduction section has been written and reviewed.

Allocated time
1 week

Start and end date for the issue/task
Start date: 15th September,2023 (Thursday), End date: 22th September 2023 (Thursday)

Who is the owner? Owner is the person in charge of the task and should be created and maintained by the owner.
Owner: 2201476, Lim Jun Hui (jhlim0079)

Task Status. Usually under "To-Do".
To-Do

What is the priority of this task?
Low priority

**Comment by jhlim0079** [comment]
1. Describe the work done in detail
The introduction for the group project report has been finished, as of 21th September 2023.

3. Has this work been committed to the repo?
The work has been committed to the Github repository as of 21th September 2023.

4. How does the work affect success of completion criteria?
The introduction covers a portion of the Milestone 1 group report that will be submitted to the client.

5. Start and end date of the work done
Start date: 15th September,2023 (Thursday), End date: 21th September 2023 (Thursday)
